// deploy/react-app/src/components/Layout.jsx
import React from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'

function Layout({ children }) {
  const { user, logout } = useAuth()
  const navigate = useNavigate()

  const handleLogout = () => {
    logout()
    navigate('/')
  }

  return (
    <div>
      <nav className="nav">
        <div className="container">
          <div className="nav-content">
            <Link to="/dashboard" className="nav-link" style={{ fontSize: '1.25rem', fontWeight: 'bold' }}>
              TicketFlow
            </Link>
            <div className="nav-links">
              <Link to="/dashboard" className="nav-link">Dashboard</Link>
              <Link to="/tickets" className="nav-link">Tickets</Link>
              <span className="nav-link">Welcome, {user?.name}</span>
              <button onClick={handleLogout} className="btn btn-secondary" style={{ padding: '0.5rem 1rem' }}>
                Logout
              </button>
            </div>
          </div>
        </div>
      </nav>
      <main>
        {children}
      </main>
    </div>
  )
}

export default Layout

// vue-app/src/components/Layout.vue
<template>
  <div>
    <nav class="nav">
      <div class="container">
        <div class="nav-content">
          <router-link to="/dashboard" class="nav-link" style="font-size: 1.25rem; font-weight: bold">
            TicketFlow
          </router-link>
          <div class="nav-links">
            <router-link to="/dashboard" class="nav-link">Dashboard</router-link>
            <router-link to="/tickets" class="nav-link">Tickets</router-link>
            <span class="nav-link">Welcome, {{ user?.name }}</span>
            <button @click="handleLogout" class="btn btn-secondary" style="padding: 0.5rem 1rem">
              Logout
            </button>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <slot />
    </main>
  </div>
</template>

<script>
export default {
  name: 'Layout',
  data() {
    return {
      user: null
    }
  },
  mounted() {
    this.getUser()
  },
  methods: {
    getUser() {
      const session = localStorage.getItem('ticketapp_session')
      if (session) {
        this.user = JSON.parse(session)
      }
    },
    handleLogout() {
      localStorage.removeItem('ticketapp_session')
      this.$router.push('/')
    }
  }
}
</script>
