// vue-app/src/views/Dashboard.vue
<template>
  <Layout>
    <div class="container" style="padding: 2rem 0">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem">
        <h1>Dashboard</h1>
        <router-link to="/tickets" class="btn btn-primary">Manage Tickets</router-link>
      </div>
      
      <div class="stats-grid">
        <div class="card stat-card">
          <span class="stat-number" style="color: var(--primary-color)">24</span>
          <div class="stat-label">Total Tickets</div>
          <p style="margin-top: 0.5rem; font-size: 0.875rem; color: var(--gray-600)">All tickets in the system</p>
        </div>
        <div class="card stat-card">
          <span class="stat-number" style="color: var(--warning-color)">8</span>
          <div class="stat-label">Open Tickets</div>
          <p style="margin-top: 0.5rem; font-size: 0.875rem; color: var(--gray-600)">Tickets waiting for action</p>
        </div>
        <div class="card stat-card">
          <span class="stat-number" style="color: var(--success-color)">12</span>
          <div class="stat-label">In Progress</div>
          <p style="margin-top: 0.5rem; font-size: 0.875rem; color: var(--gray-600)">Tickets being worked on</p>
        </div>
        <div class="card stat-card">
          <span class="stat-number" style="color: var(--gray-700)">4</span>
          <div class="stat-label">Closed</div>
          <p style="margin-top: 0.5rem; font-size: 0.875rem; color: var(--gray-600)">Resolved tickets</p>
        </div>
      </div>

      <div class="card" style="margin-top: 2rem">
        <h3 style="margin-bottom: 1rem">Quick Actions</h3>
        <div style="display: flex; gap: 1rem; flex-wrap: wrap">
          <router-link to="/tickets?create=new" class="btn btn-primary">Create New Ticket</router-link>
          <router-link to="/tickets?status=open" class="btn btn-secondary">View Open Tickets</router-link>
          <router-link to="/tickets?status=in_progress" class="btn btn-secondary">View In Progress</router-link>
        </div>
      </div>
    </div>
  </Layout>
</template>

<script>
import Layout from '../components/Layout.vue'

export default {
  name: 'Dashboard',
  components: {
    Layout
  },
  data() {
    return {
      stats: { // Initial state starts at zero
        total: 0,
        open: 0,
        inProgress: 0,
        closed: 0,
      }
    }
  },
  // When the component mounts, load the data and calculate stats
  mounted() {
    this.calculateStats()
  },
  methods: {
    calculateStats() {
      // Load raw ticket data from localStorage
      const storedTickets = localStorage.getItem('ticketapp_tickets')
      let tickets = []
      
      if (storedTickets) {
        try {
          tickets = JSON.parse(storedTickets)
        } catch (error) {
          console.error('Error parsing stored tickets:', error)
          return
        }
      }

      // Calculate the statistics
      this.stats.total = tickets.length
      this.stats.open = tickets.filter(t => t.status === 'open').length
      this.stats.inProgress = tickets.filter(t => t.status === 'in_progress').length
      this.stats.closed = tickets.filter(t => t.status === 'closed').length
    }
  }
}
</script>

// react-app/src/pages/Dashboard.jsx
// Dashboard.jsx
import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import StatsCard from '../components/StatsCard'

function Dashboard() {
  const [stats, setStats] = useState({
    total: 0,
    open: 0,
    inProgress: 0,
    closed: 0
  })

  useEffect(() => {
    // 1. Get tickets from localStorage
    const storedTickets = localStorage.getItem('ticketapp_tickets')
    let tickets = []
    if (storedTickets) {
      try {
        tickets = JSON.parse(storedTickets)
      } catch (error) {
        console.error('Error parsing stored tickets:', error)
      }
    }

    // 2. Calculate statistics
    const newStats = {
      total: tickets.length,
      open: tickets.filter(t => t.status === 'open').length,
      inProgress: tickets.filter(t => t.status === 'in_progress').length,
      closed: tickets.filter(t => t.status === 'closed').length
    }
    
    setStats(newStats)
  }, []) // Runs once on mount to get the latest stats

  return (
    <div className="container" style={{ padding: '2rem 0' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h1>Dashboard</h1>
        <Link to="/tickets" className="btn btn-primary">
          Manage Tickets
        </Link>
      </div>
      
      <div className="stats-grid">
        <StatsCard 
          title="Total Tickets" 
          value={stats.total} 
          description="All tickets in the system"
          color="primary"
        />
        <StatsCard 
          title="Open Tickets" 
          value={stats.open} 
          description="Tickets waiting for action"
          color="warning"
        />
        <StatsCard 
          title="In Progress" 
          value={stats.inProgress} 
          description="Tickets being worked on"
          color="success"
        />
        <StatsCard 
          title="Closed" 
          value={stats.closed} 
          description="Resolved tickets"
          color="gray"
        />
      </div>

      <div className="card" style={{ marginTop: '2rem' }}>
        <h3 style={{ marginBottom: '1rem' }}>Quick Actions</h3>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <Link to="/tickets?create=new" className="btn btn-primary">
            Create New Ticket
          </Link>
          <Link to="/tickets?status=open" className="btn btn-secondary">
            View Open Tickets
          </Link>
          <Link to="/tickets?status=in_progress" className="btn btn-secondary">
            View In Progress
          </Link>
        </div>
      </div>
    </div>
  )
}

export default Dashboard
